/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Icons: typeof import('./components/Icons.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    VAddTaskComponent: typeof import('./components/VAddTaskComponent.vue')['default']
    VFormFile: typeof import('./components/FormComponents/VFormFile.vue')['default']
    VInput: typeof import('./components/VInput.vue')['default']
    VInputComponent: typeof import('./components/FormComponents/VInputComponent.vue')['default']
    VModal: typeof import('./components/VModal.vue')['default']
    VNavbar: typeof import('./components/VNavbar.vue')['default']
    VNavbarLink: typeof import('./components/VNavbarLink.vue')['default']
    VSelectOption: typeof import('./components/VSelectOption.vue')['default']
  }
}
